### PR TITLE
Dark theme contribution

### PR DESCRIPTION
**Pull request by PauPau-Cor**
Change resolving #57  by adding new colors.xml file with dark theme qualifier.

line 157 in SenderRecieverService.kt is giving me an unresolvedReference error at compilation, I didn't make any changes to that part of the code or that icon so I left it as is assuming it's something wrong with my compiler.

### CODE REVIEW

**Comment by ortex** [comment]
hi @PauPau-Cor 

Could you please resolve conflicts and rebase on main?

> line 157 in SenderRecieverService.kt is giving me an unresolvedReference error at compilation, I didn't make any changes to that part of the code or that icon so I left it as is assuming it's something wrong with my compiler.

DId you try `./gradlew clean build` ? 😄

**Comment by PauPau-Cor** [comment]
`./gradlew clean build` worked, thank you!
I am still new to github, took me a while to figure out resolving the conflicts and rebasing but I think I got it, sorry for the delay.

**Comment by ortex** [comment]
> I am still new to github, took me a while to figure out resolving the conflicts and rebasing but I think I got it, sorry for the delay.

no worries :)

You merged. Not rebased

easy way to fix it:

1. sync your form with upstream https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork (just click the button on github UI)

2. exec `git fetch` in console 

3. go to your local branch `dark_theme_contribution`

4. rebase your branch on origin/main
I suppose the easiest way to do it is through android studio:

- open `VCS operations` -> `7. Branches`
image

- select `origin/main` branch in Remote Branches, select `Rebase 'dark_theme_contribution' onto 'origin/main'`

image

- resolve conflicts

image

- check that you have only correct changes and force push to `origin/dark_theme_contribution`

image

**Comment by PauPau-Cor** [comment]
Thank you for the tutorial.
I did every step and it said the reabse was successful but there doesn't seem to be any changes on the remote
I think it's because there aren't any changes to the files so it didn't push anything 😕

**Comment by ortex** [comment]
> I did every step and it said the reabse was successful but there doesn't seem to be any changes on the remote

looks like you didn't sync your for.
image

After proper sync you should see message: `This branch is up to date with roc-streaming/roc-droid:main.` 

like this:
image


Another way is configure upstream https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/configuring-a-remote-repository-for-a-fork and rebase on upstream/main

**Comment by ortex** [comment]
And about PR itself :) Looks good, thanks

I guess text color in IP address input should be fixed in dark theme
image

**Comment by gavv** [comment]
> And about PR itself :) Looks good, thanks
> 
> I guess text color in IP address input should be fixed in dark theme
> image
> 

And also tab names

**Pull request closed without merging**
