### PR TITLE
Rename package

### PR DESCRIPTION
**Pull request by ortex**
* rename package to org.rocstreaming.roctoolkit.rocdroid
* get roc-android dependency from jcenter

### CODE REVIEW

**Comment by gavv** [comment]
I think it should be `org.rocstreaming.rocdroid`, without roctoolkit?

**Comment by gavv** [comment]
Also, shouldn't we remove aar from repo now?

**Comment by ortex** [comment]
> I think it should be `org.rocstreaming.rocdroid`, without roctoolkit?

yes. fixed

**Comment by ortex** [comment]
> Also, shouldn't we remove aar from repo now?

yes, it's deleting within this PR https://github.com/roc-streaming/roc-droid/pull/9/files#diff-f853b735600c2a784c1784a78bb4dd74

**Comment by gavv** [comment]
> yes, it's deleting within this PR

Sorry, it wasn't displayed in github mobile app :/

**Comment by gavv** [comment]
LGTM!

**Pull request merged**
